# Generated by Django 3.2.5 on 2023-04-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listurls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('urloriginal', models.CharField(blank=True, max_length=300, null=True, verbose_name='Url original')),
                ('urlcorto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Url acortado')),
            ],
        ),
    ]
