# Generated by Django 3.2.5 on 2023-04-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortarurl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listurls',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
